### PR TITLE
Allow for optional spaces in the triggers and add editorconfig/yapf config

### PR DESCRIPTION
**Pull request by robbyoconnor**
Okay this should be less bad code :)

### CODE REVIEW

**Comment by cybersulu** [comment]
I don't like these changes at all. Matching is too loose and will get annoying very quickly.

**Comment by robbyoconnor** [comment]
Sorry about that :)

**Comment by robbyoconnor** [comment]
What about just for Dumpster fire?

**Comment by robbyoconnor** [comment]
actually no -- we don't always want that -- nevermind :)

**Pull request closed without merging**
